server:
  port: 8080
  
spring:
  application:
    name: catalog-service
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:8071"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true   

endpoints:
  shutdown:
    enabled: true

# info properties to see info in eureka dashboard     
info:
  app:
    name: "catalog-service"
    description: "AtoZ catalog application"
    version: 1.0.0