apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
    - name: port8761
      protocol: TCP
      port: 8761
      targetPort: 8761