apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver-deployment
  labels:
    app: authserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserver
  template:
    metadata:
      labels:
        app: authserver
    spec:
      containers:
      - name: atozmart-authserver
        image: vivekkarli/atozmart-authserver:v1
        ports:
          - containerPort: 8074
        envFrom:
          - configMapRef:
              name: atozmart-configmaps
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmaps
                key: AUTHSERVER_SPRING_DATASOURCE_URL
          - name: SPRING_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmaps
                key: AUTHSERVER_SPRING_APPLICATION_NAME
          - name: OTEL_SERVICE_NAME
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmaps
                key: AUTHSERVER_OTEL_SERVICE_NAME
          - name: SPRING_RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmaps
                key: AUTHSERVER_SPRING_RABBITMQ_HOST
          - name: SPRING_RABBITMQ_USERNAME
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmaps
                key: AUTHSERVER_SPRING_RABBITMQ_USERNAME
          - name: SPRING_RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: atozmart-secrets
                key: AUTHSERVER_SPRING_RABBITMQ_PASSWORD