server:
  port: 8761
  
spring:
  application:
    name: atozmart-eurekaserver
  config:
    import: "optional:configserver:http://localhost:8071"

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false #to avoid fetching ip addrs of all other ms
    register-with-eureka: false
    service-url: 
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/   
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}