spring:
  config:
    activate:
      on-profile: prod
       
logging:
  level:
    com.netflix.discovery.DiscoveryClient: OFF
    com.atozmart.gatewayserver: INFO
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"

