server:
   port: 8072
   ssl:
      enabled: false
      key-store: classpath:atozmart-keystore.p12
      key-store-password: '{cipher}AYAErC+yd9rviROfRbZnQmswpFZ77pAu94BZ9AgXbnHpvmHyeEcngVCxP2tJbxqeRTZ1d77EOF6PgDUoKhW+aVkwVRzlWfDzMmOOcy6WQKmxZ6OFIxhLuySoc1Dghj3WjsECzmcUgn4IenS4adp5Z0m50QWbYJ44hJgy7SkjKaP85btZrixvbmPZkbe+0NJZW0Ej3HAkRof2yZWrOY24y8HVdI/TwJB26TvwbHERLyFnuGn+Z3evqIFVA86Es/qJiZN1ZP8CjFvAu5iOpZrx3dX/YAIEz9FPm5yUVBOSTNjJKFqOJStIejIeOdfnAPrvf6T7UU+MYkjX0iTvTqkNVDO7NJGqtdiGsAPMnS5pkTAR5+XSpEMZ1PeFD/lqDCfmAvxT8hjrXkLXQjV0xiHag5JVBmFja4124HXlfcnu/GO95vkkLg02At3wMQ95DRaTUMY7G2pbvjp7xbpo6P+lXKRt1eflCTLRQ3QL/FWFDb6cadP+zVp8G5zsj+MJggSAbio0WT3QV+niecM0jcoqQ9X8u+9yt6rUJxcrjKiTMhpY0A=='
      key-store-type: PKCS12
      key-alias: atozmart-gatewayserver

spring:
   application:
      name: atozmart-gatewayserver
   config:
      import: 'optional:configserver:http://localhost:8080'
   security:
      oauth2:
         resourceserver:
            jwt:
               jwk-set-uri: http://localhost:8073/realms/atozmart/protocol/openid-connect/certs
   cloud:
      gateway:
         server:
            webflux:
               httpclient:
                  connect-timeout: 1000
                  response-timeout: 5s
               discovery:
                  locator:
                     enabled: false # disable default routes
                     lower-case-service-id: true
               routes:
               -  id: authserver-path-rewrite
                  uri: lb://ATOZMART-AUTHSERVER
                  predicates:
                  - Path=/atozmart/authserver/**
                  filters:
                  -  name: RewritePath
                     args:
                        regexp: atozmart/authserver/(?<segment>.*)
                        replacement: /${segment}
                  -  name: CircuitBreaker
                     args:
                        name: authserver
                        fallbackUri: forward:/fallback/authserver

               -  id: catalog-path-rewrite
                  uri: lb://CATALOG-SERVICE
                  predicates:
                  - Path=/atozmart/catalog/**
                  filters:
                  -  name: RewritePath
                     args:
                        regexp: atozmart/catalog/(?<segment>.*)
                        replacement: /${segment}
                  -  name: CircuitBreaker
                     args:
                        name: catalog-service
                        fallbackUri: forward:/fallback/catalog-service

               -  id: cart-path-rewrite
                  uri: lb://CART-SERVICE
                  predicates:
                  - Path=/atozmart/cart/**
                  filters:
                  -  name: RewritePath
                     args:
                        regexp: atozmart/cart/(?<segment>.*)
                        replacement: /${segment}
                  -  name: CircuitBreaker
                     args:
                        name: cart-service
                        fallbackUri: forward:/fallback/cart-service

               -  id: wishlist-path-rewrite
                  uri: lb://WISHLIST-SERVICE
                  predicates:
                  - Path=/atozmart/wishlist/**
                  filters:
                  -  name: RewritePath
                     args:
                        regexp: atozmart/wishlist/(?<segment>.*)
                        replacement: /${segment}
                  -  name: CircuitBreaker
                     args:
                        name: wishlist-service
                        fallbackUri: forward:/fallback/wishlist-service

               -  id: order-path-rewrite
                  uri: lb://ORDER-SERVICE
                  predicates:
                  - Path=/atozmart/order/**
                  filters:
                  -  name: RewritePath
                     args:
                        regexp: atozmart/order/(?<segment>.*)
                        replacement: /${segment}
                  -  name: CircuitBreaker
                     args:
                        name: order-service
                        fallbackUri: forward:/fallback/order-service

               -  id: profile-path-rewrite
                  uri: lb://PROFILE-SERVICE
                  predicates:
                  - Path=/atozmart/profile/**
                  filters:
                  -  name: RewritePath
                     args:
                        regexp: atozmart/profile/(?<segment>.*)
                        replacement: /${segment}
                  -  name: CircuitBreaker
                     args:
                        name: profile-service
                        fallbackUri: forward:/fallback/profile-service

   main:
      allow-bean-definition-overriding: true

resilience4j:
   timelimiter:
      instances:
         authserver:
            timeoutDuration: 5s
   circuitbreaker:
      configs:
         default:
            slidingWindowSize: 4
            slidingWindowType: COUNT_BASED
            failureRateThreshold: 50 # 50%
            waitDurationInOpenState: 10000 #10s
            permittedNumberOfCallsInHalfOpenState: 3
            registerHealthIndicator: true
      instances:
         authserver:
            slidingWindowSize: 8
         order-service:
            slidingWindowSize: 6
         catalog-service:
            slidingWindowSize: 6
         wishlist-service:
            slidingWindowSize: 6
         profile-service:
            slidingWindowSize: 6
         cart-service:
            slidingWindowSize: 6

eureka:
   instance:
      prefer-ip-address: true
   client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      gateway:
         access: unrestricted
      shutdown:
         access: unrestricted
      health:
         probes:
            enabled: true
   health:
      readiness-state:
         enabled: true
      liveness-state:
         enabled: true
   info:
      env:
         enabled: true
   metrics:
      tags:
         application: ${spring.application.name}

info:
   app:
      name: atozmart-gatewayserver
      description: AtoZ mart gateway server
      version: 1.0.0
logging:
   level:
      com.netflix.discovery.DiscoveryClient: OFF
      com.atozmart.gatewayserver: DEBUG

atozmart:
   auth:
      authorize-endpoint: http://localhost:8074/admin/authorize
      issuer: atozmart-authserver
   admin:
      username: atozmart_gatewayserver
      password: '{cipher}AYCMe9QHTSTP+SrBGu8Hg7z6tZrl6y0XFzDqSLLT5NgeKXLp+0bSN4v8Vd+gX9aWWjQ3gP4wiU8drGlVUXf0mEgaesunumW3xq3ZXP/dtxFsRjzxibGtFeK44Q5NTc3cCzCnv//ualI+nIAyG7SVVmh+Ww9SYka1NHWI15/3v9/FSfEZrUzRSh83oQ4+MBMtlAeXjGYfEUVXv1+cbfY5dmpJCVfpujeGY2YsWcgPtOFqghHOEdi6giR6kMjTUVhiHxbdUA8GYC6QiKMMejEosatXgHHZ2sjdQEA0ul98F7Imb4qeYzAH44MguGont10FTY+Ul3XLPmc1OjpxRzWP6WlK2bsdLagbkqReFoOZD/Saax2uR4sPrsR05KWaxBWmhFzh0tRrjqAO1lX97X2NqKtsXyDI7DegNHzMKGcUR5CrDS+8k99REo0CSkyAT6Sg/08pImXS1HkmFwKk6oxJb7i3oys6iWlc0LMW7JhHfb3pEu9AyX6y3jCdXHZoXAcIS55CkS3k/anHIiXjY8KH4dAwyz4pE6LUHYQZKfAL2xDhVw=='
   cors:
      allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      allowed-headers:
      - Authorization
      - Content-Type
      - Accept
      exposed-headers:
      - X-Access-Token
      allowed-methods:
      - GET
      - PUT
      - PATCH
      - POST
      - DELETE