server:
   port: 8074

spring:
   application:
      name: atozmart-authserver
   config:
      import: 'optional:configserver:http://localhost:8080'
   datasource:
      url: jdbc:mysql://localhost:3306/atozmart_authserver_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: '{cipher}AYBA08tZGoILTQ4cUJApsDdOE1Tt0xzgW+JqDPHR13JT6qX9ZyzRf56eAr/54tn715XKtGhu55j7E1oSY1SE08fL3uCvMYm9hKuHcWQhYooBI3sxr2lKs6edzS3NZXBsWMjIIo4HnmPIGPeh7Wsk+oYi6ZQHz6HS25dJ5jQlysElZmo4aUlOhbERp8PkRuyEjKjg4cnCHO71M7MTDDI//w8MZ9ZX3FEIpcdTHae78BsjQB7+GZpkVN9OOSEz91nwP8uYTSIBeoJIl9vsp9cIdIUQGHkMB/uKenX6k2Gwa4RBz6PSDrY4N3ofj2+s64YuHdxEhOwojx6f4/5FoyMIsfeK2FklZOZfmgRxL/PZCCtwc8P0AODme49Y+BZZppDwbnkDUCSmf2HYfEJvbbjXtelBmDrQ6g8E+tHksML/Llrvvj1nnIiBZzBUuZ2HRy/yAwlpxVm9DGnaS+fpf9U+P3g5AdcJ9jbT5nRjM3Ba5C51DkLg1g0TVWk5eojTo90460lR85NvGDwExlViH2StefYj93nMxkxPEFjiXSmCGTJKfg=='
   jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      defer-datasource-initialization: false
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            format_sql: true
   sql:
      init:
         mode: never
   cloud:
      stream:
         bindings:
            sendEmail-out-0:
               destination: send-email-topic #queue
               group: atozmart
            registerNewUser-out-0:
               destination: register-new-user-topic #queue
               group: atozmart


   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: '{cipher}AYBIbhhszkqPBSgndqUSSE8L5dy9GhQUfQmahLbMsghwjxLc23iwdgBIICQ5whj4tIXPgLndRZqcXUzdVrOJOTQdTZryfiMbKdimfZRPvY0lXUnH+d2UIRiM/D41FNG4MR5Ors7nM5WaZB7aDstQuix6+g/cWQE6P12L8pf1c5j0XTsp6aXE289KslRwyz06lR7qZdUAAB8jw84kZEh6pl9XwP7DDhQDVdvJ+ZskWQmsczbD46UV6q1ST83A088DCLmi0LACu9bkPIdUOnySC0+gBZoDq445oitdc35M26anW5bLZHd43kLWWF1AuUKc0aVDWxZ9i3zTUI8bNve4s71qM76I75m38SUhMHWVZAtFTjUBwzybVXNf/SpNJqV1Ob+m03VxOCBoU0Ztm7mxMY7j4lIo8Q3/hIS0PlOepVKuEUWCiln780OyuZUVbF/ymIXWRcNai7T+Zp6/5IT/E9PY8Yl67/id7FCBznyR0PvGjoJtVNSg8qj6xnDqhvZeZ301lC12pQ0GYIX9LBghb7Cot6IYcLjs+h59WKIXjqYoHA=='
      connection-timeout: 10s

   cache:
     type: redis
   data:
      redis:
         host: localhost
         port: 6379
     
eureka:
   instance:
      prefer-ip-address: true
   client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      shutdown:
         enabled: true
      health:
         probes:
            enabled: true
   health:
      readiness-state:
         enabled: true
      liveness-state:
         enabled: true
   info:
      env:
         enabled: true
   metrics:
      tags:
         application: ${spring.application.name}

endpoints:
   shutdown:
      enabled: true

# info properties to see info in eureka dashboard
info:
   app:
      name: atozmart-authserver
      description: AtoZ mart auth server
      version: 1.0.0

logging:
   level:
      com.netflix.discovery.DiscoveryClient: OFF
      com.atozmart.authserver: DEBUG

atozmart:
  base-url: http://localhost:3000
  reset-token-expiry: 1800 # 30 mins, in seconds
  jwt-token-expiry: 3600000 # 1 hr, in seconds
  email-verify-token-expiry: 1800 # 30 mins, in seconds
  cache-expiry: 360 # 6 mins, in seconds
  key-store-location: 
  key-store-pass: '{cipher}AYC8B8HumWSGxUyBlQRxW21YMoF5ETroemh02froii4t1MZxnTI/dRuwieIavlOY5l2injpnUlp3CMrYsAUAehx+h/UdhVepIkjARy0UUlwMO7ZhwqaXnzYzQ9z3rTepTkXi31ov6wt35nQxfweV4HA0SSTot75dfLU+o3NsPy/pz+tg2sbLclYbqMeCs9jHLMAtLcGhJCEA+jSXYNudCR1lxDsiUzDP47QWjLxTC9YGe9TdfgvwtNuDIuO+pFjzuZ8MYF1FvVqSxFEygvfBjkYg0mNSPfSObfweYDX0L184QAmKlsvU2FS+bkqtouE8fNBDsP9rwTTEhjEbyGkaql1TWB0WL64GyHPF2zJwkZmhCzav9ONkAEaBqaJsEQuiO7iwfrwUVBbq4ILs2jYGLQ+Neeqdg1JGoUBvQt4Lr1iAKqYol+/r+nUn9/WgKmMuh9OGTFP1ejOxfSLk1HbJaVhtTiissmKjd07/79BExJJsHmpcTP+76TQx7J6VOtzpysd11uznMLQpnoJiRpwpfFu3+wePjPXuoAnZnO0Q9VeYVA=='
  key-pass: '{cipher}AYArMxFGFE42ExuAK1ly4gA2xJ5vF2NnGDyp6KjgdJY76tVECdNk0nJB6WR+ax1zHkDeOul9Fe2ffgpetgzdy/+rIVL8EKd6VZfAlEXVd0CBEbprN2x+AtzmlkHNOspFD0tDrsM4cYaDZxyWVYoS4yayNtp2EYkT8z73eNLmHWMcH1C3sVTLXkVgVx8OQOkqw67uLfz4Qg4IFUOvYR208a1QmPvWaSMBPT17buitHxJrdh435E7Ev2Dp1ty86+A4/uCeigmszRExWWks+uT/p83Qhbgc6W7+VnBEfAK5g6UwbIQEr8/wlKVK29UrkLaCwuyYsBcCg4Q+Wn5eraDEtzNvPBcvWRBpT57s4Is+Kyo9MTwOcGgEjuQLdRoBwBsj5+KANGVSLahz/FBicyovqf+/JjSn4t2s078zEsg2N6p8I6YBKCufnVlg6qOZSG6epqKAsgHVP9T6aEW+WfsRFZ1z9MXxuCwthLtdGXqCR+pWMJP522yBpdlcSb34VT4jYr7UAw0egnhLG7K+Z9ncIJmn6KDQMIrSFCpHMV6HL3BKrQ=='