server:
  port: 8084

spring:
  application:
    name: order-service
  config:
    import: 'optional:configserver:http://localhost:8080'
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '{cipher}8e253ff13876d14d4309c7a1cb6e0cec80a5d2a50926baacf70b4916e20da3cb'
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  cloud:
    stream:
     bindings:
       sendEmail-out-0:
          destination: in-send-email #queue
          group: atozmart
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: '{cipher}9cd284a8f2898d63a2bc9749631f357e9cfd1818d176a7007fcb079d94bd2502'
    connection-timeout: 10s  
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
 
# info properties to see info in eureka dashboard     
info:
  app:
    name: "order-service"
    description: "AtoZ cart application"
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
           
endpoints:
    shutdown:
      enabled: true

logging:
  level:
    com.atozmart.order: DEBUG
    com.netflix.discovery.DiscoveryClient: OFF

atozmart:
  admin:
    user: 'order_service'
    password: '{cipher}44fcb05d8d5c8678f69583b3ad82944939acfe4287f80cf5282e087f21d7704e'