spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: never        
logging:
    pattern:
      level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"