server:
  port: 8085
  
spring:
  application:
    name: profile-service
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:8071"
  datasource:
    url: jdbc:mysql://localhost:3306/profiledb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: NEVER
  cloud:
    function: 
      defination: registerNewUser
    stream:
      bindings:
        registerNewUser-in-0:
          destination: in-register-user
          group: atozmart
        registerNewUser-out-0:
          destination: out-register-user #queue
          group: atozmart
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
# info properties to see info in eureka dashboard     
info:
  app:
    name: "profile-service"
    description: "AtoZ wishlist application"
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
           
endpoints:
    shutdown:
      enabled: true
   
logging:
  level:
    com.atozmart.profile: DEBUG
    com.netflix.discovery.DiscoveryClient: OFF
