server:
   port: 8085

spring:
   application:
      name: profile-service
   config:
      import: 'optional:configserver:http://localhost:8080'
   datasource:
      url: jdbc:mysql://localhost:3306/profiledb
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: '{cipher}AYDaKaoH9RnvOjZpV5LCE/BFNaYzX/ojuFyZsSgpF/iomfC0RyWRYYkY8GK11i5/B5etIpgaXonkEbp9GiZXRjj+YnVdVs21++NCCWsWnNNvXLb+SWhGHl7O0Id4DuPE26pmp8atc1mY933b6s09PIZi1g4zXcO/z+kxnm6owwt7rscQmt1gtobde+UtlrQOcWyGXev/GwlhxH8z6ZfDyVPdfNMdtDruBoquK/SR+9xqBA9wKhm1zHReMeOE5UCzzxexv52hKf00qLpGnZheX3Ir53TtUeYmTtzQXmiIqVXNiu627w/15PrO1yDFraZ9nPI25anWggaddPDQUez5qtYXrhh4E/lnSeGhfymClwiiWS79d1XIMjJEvFUXpLXRGhRcc0ogwvY5CL7W5dpeOoH/IAMJEWmScIQBwyW7lI5kasthZY7qWBnz0+cnqR2F1QU+mR9nMXy192v3420IKY7YtZCx/i8Dq4cjlktlujsDP7qglIIBlFb2UMQp3IEBTj40vqqVV16dwadFb0XWYoSBD1eFHTbYkUleQStnS6C4zQ=='
   jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            format_sql: true
   sql:
      init:
         mode: never
   cloud:
      stream:
         bindings:
            registerNewUser-in-0:
               destination: register-new-user-topic
               group: atozmart
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: '{cipher}AYAta5h4fJKI2e7hQpNdQMnD84CmgYSYC5eyJMUcsTglJCeCmpDpHEVQxLU14FM1LOiIp/iaZvZsk5df0QwZALGzssGcoBhCntFJ813lX09SQBV9ospDFmbpzRwIu1mSpcf+xfMzH9PhWzvAqBWjmly+1GvP79EZtgIRjbRFFiRYG4DzqlCoRke10Ry1u6018cYJnDjT7YroU7ITzeJWAVkS1JFBKwFSh7P81IyEHFkHyZpeYL1X/9gOgQ/GkT2eDT2/CKKQq3CnZCI7sKGwXbbmdfvdbCZFKFfoJT3ExIL5zqJ2PDiEbz3w1whsBDKaPnh0MkYBk6JgbUHMtZQAR+fGq7Hy7JRFZkqUz7SCnXI5PbSCmqBIcOSJP9h8diTbved2NsFz1sr4beNoUkip4nxA79AwTrIsiRnUY0y4LnAwuUDuIOtUwp0EU8tuPWu1KqV3MYuyIRxikbJaiUS05xE5gTenTWKC8XGJ3aCtyqo3cLWRTE2xS0ss1m+XpgLKoS0Iuj3zC9OcN4m1RET8Ms5TnqJbLqV6XMqwSLVhHzSteA=='
      connection-timeout: 10s
   cache:
      type: redis
   redis:
      host: localhost
      port: 6379

atozmart:
   cache-expiry: 360 # 6 mins, in seconds
   
eureka:
   instance:
      prefer-ip-address: true
   client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka

info:
   app:
      name: profile-service
# info properties to see info in eureka dashboard
      description: AtoZ wishlist application
      version: 1.0.0

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      shutdown:
         enabled: true
      health:
         probes:
            enabled: true
   health:
      readiness-state:
         enabled: true
      liveness-state:
         enabled: true
   info:
      env:
         enabled: true
   metrics:
      tags:
         application: ${spring.application.name}

endpoints:
   shutdown:
      enabled: true

logging:
   level:
      com.atozmart.profile: DEBUG
      com.netflix.discovery.DiscoveryClient: OFF