spring:
   application:
      name: atozmart-configserver
   profiles:
      active: git
   cloud:
      config:
         server:
            git:
               uri: https://github.com/vivekkarli/atoz-mart
               search-paths: atoz-mart-config
               default-label: main
               force-pull: true
               clone-on-start: true
               timeout: 5

encrypt:
   key: 264f450c-d078-45ca-87d9-52244e83dd49

server:
   port: 8070

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      shutdown:
         enabled: true
      health:
         probes:
            enabled: true
   health:
      readiness-state:
         enabled: true
      liveness-state:
         enabled: true
   metrics:
      tags:
         application: ${spring.application.name}