spring:
   application:
      name: atozmart-configserver
   config:
     activate:
       on-profile: prod
   cloud:
      config:
         uri: http://localhost:8888
         server:
            git:
               uri: https://github.com/vivekkarli/atoz-mart
               search-paths: atoz-mart-config
               default-label: main
               force-pull: true
               clone-on-start: true
               timeout: 5
