server:
  port: 8888

spring:
   application:
      name: atozmart-configserver
   profiles:
      active: native, default
   cloud:
      config:
         server:
            native:
              search-locations: "file:///C://my-projects//atoz-mart//atoz-mart-config"

encrypt:
  keyStore:
    location: classpath:/configserverkeypair.jks
    alias: configserverkeypair


management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      shutdown:
         enabled: true
      health:
         probes:
            enabled: true
   health:
      readiness-state:
         enabled: true
      liveness-state:
         enabled: true
   metrics:
      tags:
         application: ${spring.application.name}