server:
   port: 8085

spring:
   application:
      name: profile-service
   config:
      import: 'optional:configserver:'
   datasource:
      url: jdbc:mysql://localhost:3306/profiledb
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
   jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            format_sql: true
   sql:
      init:
         mode: NEVER
   cloud:
      stream:
         bindings:
            registerNewUser-in-0:
               destination: register-new-user-topic
               group: atozmart
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      connection-timeout: 10s

atozmart:
   admin:
      user: profile_service

eureka:
   instance:
      prefer-ip-address: true
   client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka

# info properties to see info in eureka dashboard
info:
   app:
      name: profile-service
      description: AtoZ profile application
      version: 1.0.0

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      shutdown:
         enabled: true
      health:
         probes:
            enabled: true
   health:
      readiness-state:
         enabled: true
      liveness-state:
         enabled: true
   info:
      env:
         enabled: true
   metrics:
      tags:
         application: ${spring.application.name}

logging:
   level:
      com.atozmart.profile: DEBUG
      com.netflix.discovery.DiscoveryClient: OFF