apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserverdb-deployment
  labels:
    app: authserverdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserverdb
  template:
    metadata:
      labels:
        app: authserverdb
    spec:
      containers:
      - name: atozmart-authserver-db
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmap
                key: AUTHSERVER_MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmap
                key: AUTHSERVER_MYSQL_DATABASE
        ports:
          - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: authserverdb
spec:
  selector:
    app: authserverdb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3309
      targetPort: 3306

