apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartdb-deployment
  labels:
    app: cartdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartdb
  template:
    metadata:
      labels:
        app: cartdb
    spec:
      containers:
      - name: cartdb
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmap
                key: CART_MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmap
                key: CART_MYSQL_DATABASE
        ports:
          - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: cartdb
spec:
  selector:
    app: cartdb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306