apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
  labels:
    app: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
      - name: atozmart-gatewayserver
        image: vivekkarli/gatewayserver:v1
        ports:
          - containerPort: 8072
        envFrom:
          - configMapRef:
              name: atozmart-configmap
        env:
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmap
                key: GATEWAY_SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
          - name: SPRING_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmap
                key: GATEWAY_SPRING_APPLICATION_NAME
          - name: OTEL_SERVICE_NAME
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmap
                key: GATEWAY_OTEL_SERVICE_NAME
          - name: ATOZMART_AUTH_AUTHORIZE-ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: atozmart-configmap
                key: GATEWAY_ATOZMART_AUTH_AUTHORIZE-ENDPOINT



---

apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
spec:
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072
