server:
  port: 8082
  
spring:
  application:
    name: wishlist-service
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:8071"
  datasource:
    url: jdbc:mysql://localhost:3306/wishlistdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
# info properties to see info in eureka dashboard     
info:
  app:
    name: "wishlist-service"
    description: "AtoZ wishlist application"
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
      
endpoints:
    shutdown:
      enabled: true
     
logging:
  level:
    com.atozmart.cart: DEBUG
    com.netflix.discovery.DiscoveryClient: OFF
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"
      