services:
  cart:
    image: "vivekkarli/cart:v1"
    container_name: "cart-service"
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      cartdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart
    environment:
      SPRING_APPLICATION_NAME: cart-service
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:mysql://cartdb:3306/cartdb"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8761/eureka"

  catalog:
    image: "vivekkarli/catalog:v1"
    container_name: "catalog-service"
    healthcheck:
      test: "curl --fail --silent localhost:8086/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      catalogdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:mysql://catalogdb:3306/catalogdb"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8761/eureka"
      SPRING_APPLICATION_NAME: catalog-service

  wishlist:
    image: "vivekkarli/wishlist:v1"
    container_name: "wishlist-service"
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      wishlistdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:mysql://wishlistdb:3306/wishlistdb"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8761/eureka"
      SPRING_APPLICATION_NAME: wishlist-service
  
  notification:
    image: "vivekkarli/notification-service:v1"
    container_name: "notification-service"
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      rabbitmq:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart
    environment:
      SPRING_APPLICATION_NAME: notification-service
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: prod
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8761/eureka"
      SPRING_RABBITMQ_HOST: rabbitmq

  order:
    image: "vivekkarli/order:v1"
    container_name: "order-service"
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      orderdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart
    environment:
      SPRING_APPLICATION_NAME: order-service
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:mysql://orderdb:3306/orderdb"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8761/eureka"
      SPRING_RABBITMQ_HOST: rabbitmq

  profile:
    image: "vivekkarli/profile:v1"
    container_name: "profile-service"
    healthcheck:
      test: "curl --fail --silent localhost:8085/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      profiledb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart
    environment:
      SPRING_APPLICATION_NAME: profile-service
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:mysql://profiledb:3306/profiledb"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8761/eureka"
      SPRING_RABBITMQ_HOST: rabbitmq
      
  configserver:
    image: "vivekkarli/configserver:v1"
    container_name: "atozmart-configserver"
    ports:
      - 8080:8071
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: 'main'
      SERVER_PORT: 8071
      SPRING_PROFILES_ACTIVE: prod
      ENCRYPT_KEYSTORE_PASSWORD: 123456
      ENCRYPT_KEYSTORE_SECRET: 123456

      
  eurekaserver:
    image: "vivekkarli/eurekaserver:v1"
    container_name: "atozmart-eurekaserver"
    ports:
      - 8761:8761
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      
  gatewayserver:
    image: "vivekkarli/gatewayserver:v1"
    container_name: "atozmart-gatewayserver"
    ports:
      - 8072:8072
    healthcheck:
      test: "curl --fail --silent localhost:8072/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      cart:
        condition: service_healthy
      catalog:
        condition: service_healthy
      atozmart-authserver:
        condition: service_healthy
      wishlist:
        condition: service_healthy
      notification:
        condition: service_healthy
      profile:
        condition: service_healthy
      order:
        condition: service_healthy
      #keycloak-authserver:
        #condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak-authserver:8080/realms/atozmart/protocol/openid-connect/certs"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8761/eureka"
      SPRING_APPLICATION_NAME: atozmart-gatewayserver
      ATOZMART_AUTH_AUTHORIZE-ENDPOINT: "http://atozmart-authserver:8074/admin/authorize"

  keycloak-authserver:
    image: "quay.io/keycloak/keycloak:latest"
    container_name: "keycloak-authserver"
    ports:
      - 8073:8080
    #healthcheck:
      #test: "curl --fail --silent http://localhost:8080/realms/master || exit 1"
      #interval: 10s
      #timeout: 5s
      #retries: 10
      #start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart
    volumes:
      - ../keycloak:/opt/keycloak/data/import
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: 'admin'
      KC_BOOTSTRAP_ADMIN_PASSWORD: 'admin'
    command: 
      - start-dev
      - --import-realm

  atozmart-authserver:
    image: "vivekkarli/atozmart-authserver:v1"
    container_name: "atozmart-authserver"
    healthcheck:
      test: "curl --fail --silent localhost:8074/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      atozmart-authserver-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart
    environment:
      SPRING_APPLICATION_NAME: atozmart-authserver
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:mysql://atozmart-authserver-db:3306/atozmart_authserver_db"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8761/eureka"
      SPRING_RABBITMQ_HOST: rabbitmq

  rabbitmq:
    image: "rabbitmq:4.0-management"
    container_name: "rabbitmq"
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - atozmart

  catalogdb:
    image: mysql:latest
    container_name: catalogdb
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalogdb
    networks:
      - atozmart

  cartdb:
    image: mysql:latest
    container_name: cartdb
    ports:
      - 3308:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cartdb
    networks:
      - atozmart

  wishlistdb:
    image: mysql:latest
    container_name: wishlistdb
    ports:
      - 3309:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wishlistdb
    networks:
      - atozmart
  
  atozmart-authserver-db:
    image: mysql:latest
    container_name: atozmart-authserver-db
    ports:
      - 3310:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atozmart_authserver_db
    networks:
      - atozmart
      
  orderdb:
    image: mysql:latest
    container_name: orderdb
    ports:
      - 3311:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
    networks:
      - atozmart

  profiledb:
    image: mysql:latest
    container_name: profiledb
    ports:
      - 3312:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: profiledb
    networks:
      - atozmart

networks:
  atozmart:
    driver: bridge